image: python:latest

# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

# https://pip.pypa.io/en/stable/topics/caching/
cache:
  paths:
    - .cache/pip

before_script:
  - python --version ; pip --version  # For debugging
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate
  - pip install tox

static_tests:
  script:
    - tox -e lint

unit_tests:
  script:
    - tox

pages:
  script:
    - tox -e docs
    - cp -r docs/_build/html public
  artifacts:
    paths:
      - public
